### ISSUE TITLE
Few General Questions

### ISSUE THREAD

**Issue by adithyaappu** [KlausSchaefers/quant-ux#109]
Hey Klaus,

This is not an issue, but to get some clarifications. 

I have been following the project for some time, and been playing around with it. Trying various tools and features. I am really impressed with it. I wanted to attend Quant UX Conference, but the timezone didn't allow me to. Anyway, let me jump in,

1. One major thing I notice is that design tools provided in Quant-UX are not in a polished state. Whenever I tried to do some design, I usually rand into different issues. I have been making a list in the past one month, I will share it soon. So my question is, does this meant to be a design tool? Or is it more focused on the UX and user testing part? Why I am asking this because, Even though having a free and open-source design tool is great, having a good testing platform is the need of the moment, in my opinion. **So what is the priority? Design or Testing?**

2. What is the direction of development of this tool? Specifically, where do you see **this will develop into**? For example, like an online tool like Figma? Or a desktop app focused on testing? Online/Desktop app focused on a large number of remote testing? Collaborative testing environment where documentation of results and report generation is made super easy?

3. Is there a clear **roadmap**? Is there a way to track current features being developed, or the area that someone can contribute?

4. Most part of the tool need **a lot of polishing**. Is it included in the roadmap, or are you focused on developing new features?

5. Do you need any **help with documentation part**? I love making documentation and can help with that.

6. Figma now support **interactive components**. I know it is bloody difficult to implement or import from Figma. I just want to know whether it is in the milestone.

7. I feel this project **became too complex** and that it is difficult for someone to get into. Do you feel so? If yes, what are the immediate changes you wish to see in this?

8. I'm very new to development, and still learning the basics. I have to confess that, this tool is the reason I decided to get back into development side. I am really interested to contribute in some way. I just started with JavaScript and Vue and of course it will take some time. But hopefully I will reach a level in which I can contribute. Anyway, I want to ask if you have **any good suggestions on learning resources**, please tell.

I know it's a lot. Sorry for too many questions. I thought I will keep it as a discussion thread.

**Comment by Equilibrier** [comment]
I'm sorry to step in, it might be rude, but since this is a public conversation, I would feel to comment some things over here and there:

A.1. @adithyaappu, you probably are a designer more than a developer, in my case is the opposite.  I felt the same thing with the polishing on the QuantUX part, but one thing made me very glad, that Klaus is very prompt in hearing all issues we can document in here, and very willing to take them down each, one of a time. But, it is also more than obvious that he needs help on the developing part. 
For me, sincerely it would be the first time I would contribute to a community project, but I really feel like helping, because QuantUX is helping me so much in a personal commercial project. 
I will do my best to get some time to help you Klaus, I will start maybe in a month, max two, to try to understand the code first (and Vue, as I didn't worked with it before).
Anyways, @adithyaappu , I don't feel like the tools are very unpolished, but nevertheless, if you are the designer representative in here, then you should have the final word on this, of course. I would also be very interested in reading your list of polishing zones...

A.6. Do you mean VARIANTS ? I worked with them a little,  one month ago, before taking the final step to converting all to Figma, but sincerely I'm not very impressed. I personally thing the data-binding mechanism QUX has is much much more flexbile and powerful than the variants, QUX only has to maybe bring new features in the API zone. I confess for me, the first first thing that got me into trying QUX was the prebuilt interactive components it had. In Figma, to have a simple textbox where you type words is almost impossible, and if you just want the aesthetical typing, you have to import a super complex variants model to do that, and I repeat: you can't read what you typed, this you can only do in QUX. Are you agree ? And one curiosity, do you know any other design tool out there that has this state-mechanism and data-binding integrated ? I only know QUX and for this I can always say QUX for me is the next generation of design tools, but you could debate if you want...
Anyways, I'm pretty sure the variants mechanism of figma is not the most powerful abstractization model for dealing with interactivity and I am willing to debate and to contribute to a better one though if needed, but I repeat, for me, a developer, the newly added (two days ago) <> (JS script) widget is "the last piece of the puzzle" for a complete full-blown possibility design tool, but could be polished over there and there as I discussed in this forum, with Klaus.
I personally work on a pretty complex and interactive tablet app in QUX, and I was astounished to find out that QUX, with the new <> widget is providing me the means to write >70% of the original app functionality into the prototype itself. I would never dream of doing this into Figma.
So, for me, what QUX already brought is much more powerful than what Figma would bring in the near future, or what it already has.

K.2. "I don't see Quant-UX becoming a real design tool."
Klaus, why ? Anyways, I don't want a debate on this, but for me, let me say it on all walls: QUX is already much much better than Figma, today, and could be even better tomorrow.
If it is just because of vector editing, then no worries, QUX will have that too in the future.
Any other checkpoints in here ?! :) ...

K.6. "Recreating the Figma renderer is very complex. "
When I imported my Figma project, it imported all of the screens like simple static flat images. Is this what QUX in capable of doing right now ? Then ok, it can do better.
I'm just thinking, if Figma is open-source as well, and soem guys developed some exporting tools, for generating React code, html + css etc, and you seem to have the same underlying "language" (html+css) why could it not be possible to create an equivalent of Figma components, as QUX components ? 
A conversion map can be thought in here, and of course, it will never be intended that QUX can import anything from Figma, I would personally limit myself, for the moment, just on importing the static structure of the prototype, but on at least the same granularity level, and with the most simple one-on-one mapping (Figma components <-> QUX components). Then on, QUX can work on expressing variants into JS code and so on. Vector graphics can now be converted into raster and a warning, before and after the concrete conversion can be printed, to know the user over the drawbacks of the conversion itself.

**Comment by adithyaappu** [comment]
Hey @KlausSchaefers . Thank you for responding. 

As you mentioned, I kind of felt that Quant UX is not trying to be the perfect design tool. As you said, there are enough competitors and tools available out there. So I believe user testing is going to be the core area where Quant UX will shine. 

That said, the major feature requirement will be to import design from various tools. Of course, not easy. But I think that will be needed. 

@Equilibrier on why QUX will not be a design tool. In my opinion, the main reason will be the level of sophistication needed. It is not the features, but the devil is in the details. As you said, I'm from a design background. So the major issue I face when I use QUX is some simple things in workflow. One such thing is using 'Alt' key to duplicate an element. Of course, QUX can add it or any features to compete with the Figma, but it is not worth the effort. Adobe failed to compete with Figma. Figma is developed completely with designers and collaboration in mind. [Check this as a starter. This is an old thread, but it gives an overall idea.](https://twitter.com/daveranan/status/1204836625072742402). Purely on User interface design, Figma is miles ahead of its competitors. Also, their collaborative libraries are a lifesaver. They have version control, which is unbelievable. But Figma does not have anything related to user testing, mainly on data analysis part. They are not planning to include them any time soon. But they focus purely on design. 

Also, there are some great open source design tools. [PenPot](https://penpot.app/) is an example. 

> 5. That would be great!
@KlausSchaefers  Where can I start? Where does the current documentation is situated? Are you using Gitbook?

> 6. On interactive components,
I understand that it is impossible to import it without vector handling. Image switching is a nice idea. I will try to learn more on it.

@Equilibrier it is not just variants. You can define interactions between variants. The same feature in XD is called 'States'. That is like the first step a designer will take to see some action in their prototype. Of course, if you know scripting, then it is easy. But "pure" designers repel code. Also, it is difficult for a newbie to jump right in and start coding. I'm more of a hybrid, who like coding and designing. But I used to work purely in scientific computing, based on Python and some others. Designers see these things as too techy and "non-learnable".

Interaction design is a whole different field in UX. Interactive component helps to do that to some extent in Figma. You can look into ProtoPie or similar tools for more. 

On widgets in QUX, of course, that is what makes QUX awesome. I even tried to migrate completely into QUX, but some needed basic things were missing. I will add about it soon.

And I don't think there is battle or anything. But the approach in thinking is also not very different. Adobe's reliance on layers comes from their ultimate photo editing tool, Photoshop. Adobe needed that approach to build an ecosystem, in which various programmes will work together. This is a marketing decision they made. See, it is much cheaper to opt for all the CC apps together than purchasing one or two. Also, the similarity helps users to learn the new tool easily. For example, if you know Photoshop, learning Illustrator will be a little easy. If you know illustrator, learning XD is a cakewalk. It is more like Adobe vs rest of the world, in my opinion, not designers vs developers. Again, this is a personal opinion. 

7. @KlausSchaefers more towards usability and documentation. I think QUX now have the "scientific/techy" feel (which I like, but most don't).

Also, I understand the idea @Equilibrier trying to say, the map between Figma and QUX, but I don't think that is straight forward.

**Comment by Equilibrier** [comment]
> Also, I understand the idea @Equilibrier trying to say, the map between Figma and QUX, but I don't think that is straight forward.
@adithyaappu Surely it will not be straight-forward, but if you're right and QUX will base it's purpose on testing the UI prototypes, then, I'm thinking you don't have to import any aspect of Figma into QUX, but only the screens, the primitives and the interaction (which should be >95% the same). I know it looks like everything, but at least you would not need vector graphics in here, right ? The testing is only about running the prototype and see what were the common clicks and transitions if I understand it correctly.
I don't know where the difficulty lies, maybe you are referring it into the variants zone ("interactions in Figma") but nevertheless, in the programming field speaking, this should also be doable, just because of the fact that QUX's script widgets have the solutions set inclusive of the Figma's variants mechanism (anything you would do with Figma's variants can always be translated into JS code).

**Comment by KlausSchaefers** [comment]
@adithyaappu Hi, the documentation are basically JS files with strings. Take a look here:

https://github.com/KlausSchaefers/quant-ux/tree/master/src/help/en

https://github.com/KlausSchaefers/quant-ux/blob/master/src/services/HelpService.js

If you want to add a new Topic, 1) create a new file and register it in the 2) HelpService. Images would go to public/help

If you need more help, please let me know.

**Comment by KlausSchaefers** [comment]
> Also, I understand the idea @Equilibrier trying to say, the map between Figma and QUX, 
> but I don't think that is straight forward.

The other project https://luisa.cloud is actually the result of my efforts to integrate Figma. I found a quite good 1:1 mapping the the Quant-UX data model:

https://github.com/KlausSchaefers/vue-low-code/blob/master/src/qux/figma/FigmaService.js

However vectors and some other things are the tricky part. Whenever there is no direct mapping one has to fall back to PNGs. For Luisa this is ok, but the Quant-UX backend is not designed to have a million small files, thus I decided to simply flatten all screens and add hotspots where needed. Also, other testing tools like Maze & Useberry simply do flat imports. So QUX is in those regards not too bad 😄 

I was also looking into interactive components, but this is a tricky task that I couldn't complete yet. Although I like the idea, I am not sure if this fits the domain of Quant-UX. The main goal was / is to enable designers very early to make informed decisions about a design and not guess.

@adithyaappu I am very much looking forward to you list of improvements! I will add already one issue of "ALT Copy". Thanks.

**Comment by Equilibrier** [comment]
@KlausSchaefers don;t you think scripting can be the enough base-support for auto-implementing any interactive-figma-components behavior transparent for any designer ? You want the look and feel of the prototype to be exactly the one when running it in Figma right ? If not, you would loose your testing&user feedback target.
I do think you can generate script code for any interactive variants a figma project can bring, and you can keep QUX in the area of testing only by not providing interactive as QUX functionality. Hence you may think like this: "I implemented <> scripts mainly for importing Figma variants 100% the same behavior, but without adding the visuals for this concept".

**Comment by KlausSchaefers** [comment]
> Personally I'm very controversed about why QUX is not popular already

 am asking that my self for a long time :D

**Comment by KlausSchaefers** [comment]
> @KlausSchaefers don't you think scripting can be the enough base-support for auto-implementing any interactive-figma-components behavior transparent (they don't need to touch the code) for any designer ?
> 
> I think you really want the look and feel of the prototype to be exactly the one when running it in Figma, right ? Because if don't, I think you would loose the very basic of your testing&user feedback functionality idea.
> 
> I do think you can generate script code for any interactive variants a figma project can bring, and you can keep QUX in the area of testing only by *not providing interactive as QUX functionality. _Hence you may think like this: "I implemented <> scripts mainly for importing Figma variants with 100% the same behavior, but without adding the visuals for this concept in QUX itself"._

No, interactive components need to be implemented over the normal state machine (the lines). Scripting is not a solution for this. You are right, the import must be 100% pixel perfect.

**Comment by KlausSchaefers** [comment]
I will close this for now.
