### ISSUE TITLE
component based solution

### ISSUE THREAD

**Issue by ui3o** [KlausSchaefers/quant-ux#16]
Hi!

Fist of all, thank you for your amazing idea!

Is there any way to make not just group, like component in figma? I mean when I modify a group, the others can inherit the component position change inside the group  or label or more?

Thank you for your job, and answer!

**Comment by KlausSchaefers** [comment]
There are the symbols, but they just apply to styles. You can also create symbols of groups, but the updates are limited. To create symbol, select an element and click on the "Make Symbol" button.
![Quant-UX-Prototype-Test-and-Learn-3-0-31 (2)](https://user-images.githubusercontent.com/7108416/94852561-fb363e00-0421-11eb-8f22-2e3ff9b00c20.png)

**Comment by KlausSchaefers** [comment]
Making more advanced components will need some time. Can you name some examples of the functionality?

**Comment by ui3o** [comment]
Yes sure! Thank you for your reply! 

I will attach an example usage! I think if you can add this feature, than your program can be better than figma!

![Peek 2020-10-02 14-19](https://user-images.githubusercontent.com/43638725/94922601-cf1acb80-04ba-11eb-8c07-dbd6d0a74502.gif)

If you need any programming knowledge I can help you in it!

**Comment by bmcgonag** [comment]
So, what happens if you create the child, modify the parent, and thus the child is modified, then modify the child (so the parent and child are no longer in sync), but then you modify the parent element again?  Do you expect the child to get that same modification?  Or, once the child is modified independent of the parent, is it no longer bound?

**Comment by KlausSchaefers** [comment]
Started to work on this, but it is a really tricky one. There are quite a lot of weird edge cases... Hopefully I can realise a first beta during April. For those interested the first bits of code are GIT, so you could try locally...

**Comment by KlausSchaefers** [comment]
Hi @ui3o,

I have just released a beta of this feature. It is still a little hidden, because it is still in beta. To use this:

a) Create some kind of group
b) Turn the group into a component
c) update the component, e.g. drag and drop new elements into the group
d) Select the component and click on "Update all instances"

I still intend to make the last step automatic. Here is a video:

https://user-images.githubusercontent.com/7108416/162612616-6377093e-025f-4da6-aca5-5b2322fa4f9b.mp4


Thanks for the idea.
