### ISSUE TITLE
Communicating between Quant-UX and an embedding page

### ISSUE THREAD

**Issue by mashedkeyboard** [KlausSchaefers/quant-ux#211]
Hi folks,

I'm trying to use Quant-UX for some university research - it's proving incredibly helpful so far :)

Using it for some user testing, I want to embed it into an external survey, ideally - in doing so, though, I need to pass some information between the two (either which of a set of A-B tests was selected in Quant-UX needs to be passed to the survey software, or alternatively which was selected by the survey software to be sent into Quant-UX).

I had been hoping to do this by using the `window.postMessage` api, but it appears that the Quant-UX script widget doesn't allow access to `window`, and as a consequence I'm not sure that route will work. Are there any better ideas? For instance, is there any way to provide a parameter to the URL launching the prototype to be passed into the prototype?

The only alternative I've been able to come up with so far would be the survey software making a web request to some other external API I set up, and then Quant-UX later making a request to it for the same data using a Web Service widget, which while possible is a bit of a pain! I'd very much like to hear better suggestions :)

**Comment by KlausSchaefers** [comment]
Hi,

using the `postMessage` api is not possible because scripts are running in a web worker for security reasons. 

I think the easiest would be to enable the simulator to read some URL variables. By doing so, you could pass in which experiment, A or B, you want to run.

I could imagine the following url format:

```
https://quant-ux.com/#/test.html?h=<test_id>&log=true&data_<variabe_name>=<variable_value>
```

So to pass the experiment the url could look like `...&data_experiment=a`.

In the prototype you would use a normal OR operator instead of A/B.

Would this work for you?

Klaus

**Comment by mashedkeyboard** [comment]
Thanks so much for the quick response, Klaus! Something like that would work perfectly, I guess they'd then align with data bindings to be pulled through into the rest of the application and then could attach to the OR. Is there a way to record the data binding alongside the results at the end as well, so for instance a participant ID could be included to match up to the rest of the study information?

**Comment by KlausSchaefers** [comment]
Hi,

I have added the URL parsing now to the simulator. Try out the following URL:

https://quant-ux.com/#/test.html?h=a2aa10aEcpoN9I5GoeUkiBzgj0fseGI5Rlni9gb38imUIGFqYyqszySd2ic2&log=true&**data_experiment=b&data_participant=klauss**

You can see that I have added the following parameters `data_experiment=b&data_participant=klauss`. When you load the test, the values will be shown on the start page, because the labels are bound the the variables. 

![image](https://user-images.githubusercontent.com/7108416/210893567-49be437a-a104-4184-922f-5b9b12649e8c.png)

Also the OR navigation will now navigate based in the 'experiment' variable.

![image](https://user-images.githubusercontent.com/7108416/210893472-6c5977f8-56fd-4c68-b4b1-7f5c5f3126be.png)

When you update the URL variables and reload the page, the new values should be shown.

You can use the variables for instance in a REST call to send data to a server.

Does this help?

**Comment by mashedkeyboard** [comment]
That looks like exactly the sort of thing that would make that work - thank you so much! :)

Issue closed by https://github.com/KlausSchaefers/quant-ux/commit/6ea767e2ab8efc86b910ccce0698b4649ed4c7f8 :)
