### ISSUE TITLE
is there an HTML widget? an IFrame widget?

### ISSUE THREAD

**Issue by rozek** [KlausSchaefers/quant-ux#273]
First of all: thank you very much for this impressive work!

I'm currently experimenting a bit with Quant-UX - an immediately ran into a number of problems:

- background images can not be "repeated" across a screen or widget (aka "tiling")?
- is it possible to provide explicit HTML contents to be rendered?
- or: is there an IFrame widget that shows embedded web pages?

Thanks in advance for your effort!

**Comment by KlausSchaefers** [comment]
Hi,

1) This is a nice idea. I just added a new option to the new release:

![image](https://github.com/KlausSchaefers/quant-ux/assets/7108416/083c38fc-de4d-4254-9305-863c6023c9fa)

You can try out here: https://dev.quant-ux.com/

2) No, this will not be possible due to security risks.

3) This might be possible, but it might mess with the screen recordings etc. These are replays with live rendering, kind of animations. If at the replay time, the Iframe content is different, the video would be false. So, I am kind of hesitant.

Thanks for reaching out!

Klaus

**Comment by rozek** [comment]
Wow, thanks, that was quick!

However: the given image still seems to be scaled before it gets repeated - is that correct? Most often, however, textures should be used in their original size!

Another remark: I do not understand your response to my third question: won't product videos always be "wrong" as soon as some external (or random) content is used? What distinguishes a "web service" from an external web page with respect to what a prototype shows on screen and what is recorded in a video?
